# -*- mode: ruby -*-
# vi: set ft=ruby :

vm_name = "homesensor-backend"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20201014.0.0"

  config.vm.provider "virtualbox" do |vb|
    vb.name = vm_name
    vb.memory = "1024"
    vb.cpus = 1
	
	# See: https://github.com/hashicorp/vagrant/issues/11777
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end

  config.vm.hostname = vm_name
  config.vm.synced_folder "./ansible/", "/vagrant/ansible"
  config.vm.network "forwarded_port", guest: 8123, host: 8123	# HomeAssistant Web-GUI
  config.vm.network "forwarded_port", guest: 1883, host: 1883	# HomeAssistant MQTT broker

  # remove not yet supported ansible ppa
  config.vm.provision "shell",
    inline: "rm -f /etc/apt/sources.list.d/ansible-ansible-focal.list"

  config.vm.provision "ansible_local" do |ansible|
    ansible.install_mode = "pip"
    ansible.playbook = "/vagrant/ansible/playbook-vm.yml"
  end

end
