name: backend_deployment

on: [push, pull_request]

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - centos-7
          - debian-9
          - fedora-28
          - ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Molecule converge
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: --debug
          molecule_command: converge
          molecule_args: --scenario-name ${{ matrix.scenario }}
          molecule_working_dir: ./backend/ansible/
